title: Thallium's Blog
description: My blog for competive programming and life
author: Gengchen Thallium Tuo
avatar: /logo.jpg
email: tuogengchen@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: gengchen233
  card: summary
logo: logo.png
social:
  name: Gengchen Thallium Tuo
  links:
    - https://twitter.com/gengchen233
    - https://github.com/thallium
    - https://codeforces.com/profile/Thallium54
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en

skin: daylight
